// export const SUCCESS = "ALERT_SUCCESS";
// export const ERROR = "ALERT_ERROR";
// export const CLEAR = "ALERT_CLEAR";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// ---- REGISTER ----
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// ---- LOGIN ----
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// ---- LOGOUT ----
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
// ---- AUTH ----
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const RECOVER_PASSWORD = "RECOVER_PASSWORD";
export const RECOVER_PASSWORD_FAIL = "RECOVER_PASSWORD_FAIL";
// ---- PRODUCT ----
export const UPLOAD_PRODUCT_REQUEST = "UPLOAD_PRODUCT_REQUEST";
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS";
export const UPLOAD_PRODUCT_FAIL = "UPLOAD_PRODUCT_FAIL";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_FAIL = "GET_BRANDS_FAIL";
export const GET_TYPES_OF_SALE_FAIL = "GET_TYPES_OF_SALE_FAIL";
export const GET_TYPES_OF_SALE = "GET_TYPES_OF_SALE";
export const GET_SIZES = "GET_SIZES";
export const GET_SIZES_FAIL = "GET_SIZES_FAIL";
export const GET_LENGTHS = "GET_LENGTHS";
export const GET_LENGTHS_FAIL = "GET_LENGTHS_FAIL";
export const GET_OCCASIONS = "GET_OCCASSION";
export const GET_OCCASIONS_FAIL = "GET_OCCASSION_FAIL";
export const GET_EVENTS = "GET_TYPE_OF_EVENTS";
export const GET_EVENTS_FAIL = "GET_TYPE_OF_EVENTS_FAIL";
export const GET_COLORS = "GET_COLORS";
export const GET_COLORS_FAIL = "GET_COLORS_FAIL";
export const GET_SPECIAL_OCCASIONS = "GET_SPECIAL_OCCASIONS";
export const GET_SPECIAL_OCCASIONS_FAIL = "GET_SPECIAL_OCCASIONS_FAIL";

// -------------------
// ---- ADMIN ----
export const GETALL_REQUEST = "GETALL_REQUEST";
export const GETALL_SUCCESS = "GETALL_SUCCESS";
export const GETALL_FAILURE = "GETALL_FAILURE";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";
