// export const SUCCESS = "ALERT_SUCCESS";
// export const ERROR = "ALERT_ERROR";
// export const CLEAR = "ALERT_CLEAR";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// ---- REGISTER ----
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// ---- LOGIN ----
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// ---- LOGOUT ----
export const LOGOUT = "LOGOUT";
// ---- AUTH ----
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
// ---- PRODUCT ----
export const UPLOAD_PRODUCT_REQUEST = "UPLOAD_PRODUCT_REQUEST";
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS";
export const UPLOAD_PRODUCT_FAIL = "UPLOAD_PRODUCT_FAIL";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const GET_SIZES = "GET_SIZES";
export const GET_COLORS = "GET_COLORS";
export const GET_BRAND = "GET_BRAND";

// -------------------
// ---- ADMIN ----
export const GETALL_REQUEST = "GETALL_REQUEST";
export const GETALL_SUCCESS = "GETALL_SUCCESS";
export const GETALL_FAILURE = "GETALL_FAILURE";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";
